export const START_REQUEST = 'START_REQUEST';
export const SUCCESS_REQUEST = 'SUCCESS_REQUEST';
export const ERROR_REQUEST ='ERROR_REQUEST';


export const GET_ASSOCIATION_TABLE_SAGA = 'GET_ASSOCIATION_TABLE_SAGA';
export const ADD_ASSOCIATION_TABLE = 'ADD_ASSOCIATION_TABLE';
export const EDIT_ASSOCIATION_TABLE_ITEM = 'EDIT_ASSOCIATION_TABLE';
export const DELETE_ASSOCIATION_TABLE_ITEM = 'DELETE_ASSOCIATION_TABLE_ITEM';