export const START_REQUEST = 'START_REQUEST';
export const SUCCESS_REQUEST = 'SUCCESS_REQUEST';
export const ERROR_REQUEST ='ERROR_REQUEST';


export const GET_ASSOCIATION_TABLE_SAGA = 'GET_ASSOCIATION_TABLE_SAGA';
export const ADD_ASSOCIATION_TABLE = 'ADD_ASSOCIATION_TABLE';
export const EDIT_ASSOCIATION_TABLE_ITEM = 'EDIT_ASSOCIATION_TABLE';
export const DELETE_ASSOCIATION_TABLE_ITEM = 'DELETE_ASSOCIATION_TABLE_ITEM';


export const INIT_TABLE_SAGA = 'INIT_TABLE_SAGA';
export const ADD_TABLE = 'ADD_TABLES';
export const ADD_TABLE_ITEM = 'ADD_TABLE_ITEM';
export const ADD_TABLE_COLUMNS = 'ADD_TABLE_COLUMNS';
export const EDIT_TABLE_ITEM = 'EDIT_TABLE_ITEM';
export const DELETE_TABLE_ITEM = 'DELETE_TABLE_ITEM';

export const INIT_EDIT_TABLE_ITEM_SAGA = 'INIT_EDIT_TABLE_ITEM_SAGA';
export const INIT_CREATE_TABLE_ITEM_SAGA = 'INIT_CREATE_TABLE_ITEM_SAGA';
export const DELETE_TABLE_ITEM_SAGA = 'DELETE_TABLE_ITEM_SAGA';